### ISSUE TITLE
empty Uint8Array fails to encode

### ISSUE THREAD

**Issue by wanderer** [dignifiedquire/borc#13]
empty Uint8Array fails to encode

**Comment by wanderer** [comment]
actully all Uint8Array fail :(

```
const cbor = require('./')

const array = new Uint8Array([0, 0])
let encoded = cbor.encode(array) // returns <Buffer f5>
const obj = cbor.decodeFirst(encoded)
console.log(obj)
```
results in 
```
/home/null/code/borc/src/encoder.js:458
          result[i].copy(res, index)
                    ^

TypeError: result[i].copy is not a function
    at Encoder.finalize (/home/null/code/borc/src/encoder.js:458:21)
    at Object.encode (/home/null/code/borc/src/encoder.js:505:16)
    at Object.<anonymous> (/home/null/code/borc/test.js:5:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:422:7)

```

**Comment by dignifiedquire** [comment]
That's probably because they are so similar to `Buffer` but not quite the same thing..
