### ISSUE TITLE
`null` fails to encode

### ISSUE THREAD

**Issue by wanderer** [dignifiedquire/borc#14]
```
const cbor = require('borc')

let encoded = cbor.encode(null) // returns <Buffer f5>
const obj = cbor.decodeFirst(encoded)
console.log(obj)
```

results in 

```
assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: false == true
    at Object.<anonymous> (/home/null/code/borc/test.js:7:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
    at bootstrap_node.js:537:3

```

**Comment by wanderer** [comment]
my mistake!
