### ISSUE TITLE
Fails to decode arrays with over 255 elements

### ISSUE THREAD

**Issue by wanderer** [dignifiedquire/borc#20]
Fails to decode arrays with over 255 elements with the following
```
/home/null/code/borc/src/decoder.js:561
        throw new Error('Undeterminated nesting')
        ^

Error: Undeterminated nesting
    at Decoder._decode (/home/null/code/borc/src/decoder.js:561:15)
    at Decoder.decodeFirst (/home/null/code/borc/src/decoder.js:577:10)
    at Object.<anonymous> (/home/null/code/js-primea-iframe-container/examples/ipfstest.js:18:5)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
```
source
```javascript
content = Array(256).fill(0)
const encoded = cbor.encode(content)
const dec = new cbor.Decoder()
dec.decodeFirst(encoded)
```

**Comment by dignifiedquire** [comment]
Turns out I had the wrong return code for `array_16`. Sorry about that, should be fixed in #21

**Comment by wanderer** [comment]
awesome!

**Comment by wanderer** [comment]
oh maybe i should wait to close until merged :P
